### PR TITLE
add initial fastlane structures

### PR DESCRIPTION
**Pull request by IzzySoft**
In case you consider inclusion with [F-Droid](https://f-droid.org/) – but also helpful with deployment to Play Store (which might need the Fastlane binaries, though).

### CODE REVIEW

**Comment by IzzySoft** [comment]
PS: if you want to add more Fastlane details (like screenshots or per-release changelogs), my [cheat-sheet](https://gitlab.com/snippets/1895688) might prove helpful :wink:

**Comment by IzzySoft** [comment]
@green-green-avk anything wrong with my PR? I was hoping it would make it before today's release :wink:

**Comment by IzzySoft** [comment]
@green-green-avk some feedback would be nice. If you aren't interested in this, that's fully OK – but a short statement then would be appreciated. If clarification is needed, let me know and I try to answer your questions. Thanks!

**Comment by IzzySoft** [comment]
@green-green-avk any chance this will be processed? I'm about cleaning up my Github account before this year's end and drop "old forks" I don't plan to maintain – and once I drop the fork of your app, this PR will go "stale" as the source is gone.

**Comment by green-green-avk** [comment]
Sorry for this enormous delay... Done.

**Comment by IzzySoft** [comment]
Thanks a lot! Adjusted the config in my repo to check this whenever picking a release. Should you add additional elements (e.g. start with screenshots, or per-release changelogs) please let me know so I can check and enable them as well. Some hints on formatting the `full_description.txt` can [be found here](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Fastlane) (I recommend what I call "Markdown light" there, as it works best with multiple "markets"). When in doubt, feel free to ask.

**Pull request merged**
